// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TH.Auth.Infrastructure;

#nullable disable

namespace TH.WebAPI.Migrations
{
    [DbContext(typeof(AuthDbContext))]
    [Migration("20260505150047_AuthV1")]
    partial class AuthV1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TH.Auth.Domain.MFA.AuthAuditLog", b =>
                {
                    b.Property<int>("auditID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("auditID"));

                    b.Property<string>("action")
                        .HasColumnType("text");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("detail")
                        .HasColumnType("text");

                    b.Property<string>("ip")
                        .HasColumnType("text");

                    b.Property<string>("result")
                        .HasColumnType("text");

                    b.Property<string>("userAgent")
                        .HasColumnType("text");

                    b.Property<int?>("userID")
                        .HasColumnType("integer");

                    b.HasKey("auditID");

                    b.HasIndex("userID");

                    b.ToTable("AuthAuditLog", "auth");
                });

            modelBuilder.Entity("TH.Auth.Domain.MFA.AuthMfaSecret", b =>
                {
                    b.Property<int>("mfaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("mfaID"));

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("enabledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("enrollmentStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("isEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("label")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("lastVerifiedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("recoveryCodes")
                        .HasColumnType("text");

                    b.Property<string>("secret")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("userID")
                        .HasColumnType("integer");

                    b.HasKey("mfaID");

                    b.HasIndex("userID")
                        .IsUnique();

                    b.HasIndex("userID", "type")
                        .IsUnique();

                    b.ToTable("AuthMfaSecret", "auth");
                });

            modelBuilder.Entity("TH.Auth.Domain.MFA.AuthUserSession", b =>
                {
                    b.Property<int>("sessionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("sessionID"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("deviceId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ip")
                        .HasColumnType("text");

                    b.Property<bool>("isRevoked")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("lastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("userAgent")
                        .HasColumnType("text");

                    b.Property<int>("userID")
                        .HasColumnType("integer");

                    b.HasKey("sessionID");

                    b.HasIndex("userID");

                    b.ToTable("AuthUserSession", "auth");
                });

            modelBuilder.Entity("TH.Auth.Domain.Role.AuthPermission", b =>
                {
                    b.Property<int>("permissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("permissionID"));

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("permissionDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("permissionName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("scope")
                        .HasColumnType("text");

                    b.HasKey("permissionID");

                    b.ToTable("AuthPermission", "auth");
                });

            modelBuilder.Entity("TH.Auth.Domain.Role.AuthRole", b =>
                {
                    b.Property<int>("roleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("roleID"));

                    b.Property<bool>("isDefault")
                        .HasColumnType("boolean");

                    b.Property<string>("roleDescription")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("roleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("scope")
                        .HasColumnType("text");

                    b.HasKey("roleID");

                    b.HasIndex("roleName")
                        .IsUnique();

                    b.ToTable("AuthRole", "auth");

                    b.HasData(
                        new
                        {
                            roleID = 1,
                            isDefault = false,
                            roleDescription = "Quản trị viên hệ thống",
                            roleName = "admin_he_thong",
                            scope = "staff"
                        },
                        new
                        {
                            roleID = 2,
                            isDefault = false,
                            roleDescription = "Kế toán tài sản cố định",
                            roleName = "ke_toan_tscd",
                            scope = "staff"
                        },
                        new
                        {
                            roleID = 3,
                            isDefault = false,
                            roleDescription = "Trưởng phòng kế toán",
                            roleName = "truong_phong_ke_toan",
                            scope = "staff"
                        },
                        new
                        {
                            roleID = 4,
                            isDefault = false,
                            roleDescription = "Kỹ thuật viên",
                            roleName = "ky_thuat_vien",
                            scope = "staff"
                        },
                        new
                        {
                            roleID = 5,
                            isDefault = false,
                            roleDescription = "Trưởng phòng kỹ thuật",
                            roleName = "truong_phong_ky_thuat",
                            scope = "staff"
                        },
                        new
                        {
                            roleID = 6,
                            isDefault = false,
                            roleDescription = "Giám đốc",
                            roleName = "giam_doc",
                            scope = "staff"
                        },
                        new
                        {
                            roleID = 7,
                            isDefault = false,
                            roleDescription = "Phó giám đốc",
                            roleName = "pho_giam_doc",
                            scope = "staff"
                        },
                        new
                        {
                            roleID = 8,
                            isDefault = false,
                            roleDescription = "Trưởng phòng ban",
                            roleName = "truong_phong_ban",
                            scope = "staff"
                        },
                        new
                        {
                            roleID = 9,
                            isDefault = true,
                            roleDescription = "Nhân viên",
                            roleName = "nhan_vien",
                            scope = "staff"
                        },
                        new
                        {
                            roleID = 10,
                            isDefault = false,
                            roleDescription = "Nhân viên nhân sự",
                            roleName = "nhan_vien_nhan_su",
                            scope = "staff"
                        });
                });

            modelBuilder.Entity("TH.Auth.Domain.Role.AuthRolePermission", b =>
                {
                    b.Property<int>("rolePermissionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("rolePermissionID"));

                    b.Property<int>("permissionID")
                        .HasColumnType("integer");

                    b.Property<int>("roleID")
                        .HasColumnType("integer");

                    b.HasKey("rolePermissionID");

                    b.HasIndex("permissionID");

                    b.HasIndex("roleID");

                    b.ToTable("AuthRolePermission", "auth");
                });

            modelBuilder.Entity("TH.Auth.Domain.Role.AuthUserRole", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    b.Property<int>("roleID")
                        .HasColumnType("integer");

                    b.Property<DateTime>("assignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("userID", "roleID");

                    b.HasIndex("roleID");

                    b.ToTable("AuthUserRole", "auth");

                    b.HasData(
                        new
                        {
                            userID = 1,
                            roleID = 6,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 2,
                            roleID = 7,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 3,
                            roleID = 7,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 4,
                            roleID = 9,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 5,
                            roleID = 3,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 6,
                            roleID = 2,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 7,
                            roleID = 9,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 8,
                            roleID = 9,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 9,
                            roleID = 9,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 10,
                            roleID = 8,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 10,
                            roleID = 10,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 11,
                            roleID = 10,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 12,
                            roleID = 5,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 13,
                            roleID = 4,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 14,
                            roleID = 4,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 15,
                            roleID = 8,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 16,
                            roleID = 9,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 17,
                            roleID = 9,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 18,
                            roleID = 9,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 19,
                            roleID = 9,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 20,
                            roleID = 8,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 21,
                            roleID = 9,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 22,
                            roleID = 9,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 23,
                            roleID = 9,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 24,
                            roleID = 9,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 25,
                            roleID = 9,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 26,
                            roleID = 9,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 27,
                            roleID = 9,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 28,
                            roleID = 9,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 29,
                            roleID = 9,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 30,
                            roleID = 8,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 31,
                            roleID = 9,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 32,
                            roleID = 9,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 33,
                            roleID = 8,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 34,
                            roleID = 9,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            userID = 35,
                            roleID = 9,
                            assignedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("TH.Auth.Domain.Token.AuthEmailVerification", b =>
                {
                    b.Property<int>("emailVerificationID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("emailVerificationID"));

                    b.Property<string>("codeHash")
                        .HasColumnType("text");

                    b.Property<DateTime?>("consumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("expiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("userID")
                        .HasColumnType("integer");

                    b.HasKey("emailVerificationID");

                    b.HasIndex("userID");

                    b.ToTable("AuthEmailVerification", "auth");
                });

            modelBuilder.Entity("TH.Auth.Domain.Token.AuthPasswordReset", b =>
                {
                    b.Property<int>("passwordResetID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("passwordResetID"));

                    b.Property<string>("codeHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("consumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("expiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("purpose")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("userID")
                        .HasColumnType("integer");

                    b.HasKey("passwordResetID");

                    b.HasIndex("userID");

                    b.ToTable("AuthPasswordReset", "auth");
                });

            modelBuilder.Entity("TH.Auth.Domain.Token.AuthRefreshToken", b =>
                {
                    b.Property<int>("refreshTokenID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("refreshTokenID"));

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedByIp")
                        .HasColumnType("text");

                    b.Property<DateTime>("Expires")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ReplacedByToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("Revoked")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RevokedByIp")
                        .HasColumnType("text");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("sessionID")
                        .HasColumnType("integer");

                    b.Property<int>("userID")
                        .HasColumnType("integer");

                    b.HasKey("refreshTokenID");

                    b.HasIndex("sessionID");

                    b.HasIndex("userID");

                    b.ToTable("AuthRefreshToken", "auth");
                });

            modelBuilder.Entity("TH.Auth.Domain.User.AuthProfile", b =>
                {
                    b.Property<int>("profileID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("profileID"));

                    b.Property<string>("avatar")
                        .HasColumnType("text");

                    b.Property<DateTime?>("dateOfBirth")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("firstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("gender")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("lastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("userID")
                        .HasColumnType("integer");

                    b.HasKey("profileID");

                    b.HasIndex("userID")
                        .IsUnique();

                    b.ToTable("AuthProfile", "auth");

                    b.HasData(
                        new
                        {
                            profileID = 1,
                            firstName = "Phạm Quốc",
                            gender = "Nam",
                            lastName = "Hùng",
                            userID = 1
                        },
                        new
                        {
                            profileID = 2,
                            firstName = "Trần Thanh",
                            gender = "Nam",
                            lastName = "Tùng",
                            userID = 2
                        },
                        new
                        {
                            profileID = 3,
                            firstName = "Nguyễn Thị Minh",
                            gender = "Nữ",
                            lastName = "Châu",
                            userID = 3
                        },
                        new
                        {
                            profileID = 4,
                            firstName = "Lê Quang",
                            gender = "Nam",
                            lastName = "Bình",
                            userID = 4
                        },
                        new
                        {
                            profileID = 5,
                            firstName = "Nguyễn Thị",
                            gender = "Nữ",
                            lastName = "Hương",
                            userID = 5
                        },
                        new
                        {
                            profileID = 6,
                            firstName = "Lê Bảo",
                            gender = "Nữ",
                            lastName = "Ngọc",
                            userID = 6
                        },
                        new
                        {
                            profileID = 7,
                            firstName = "Trần Văn",
                            gender = "Nam",
                            lastName = "Hải",
                            userID = 7
                        },
                        new
                        {
                            profileID = 8,
                            firstName = "Phạm Thị",
                            gender = "Nữ",
                            lastName = "Mai",
                            userID = 8
                        },
                        new
                        {
                            profileID = 9,
                            firstName = "Võ Xuân",
                            gender = "Nam",
                            lastName = "Trường",
                            userID = 9
                        },
                        new
                        {
                            profileID = 10,
                            firstName = "Hoàng Thu",
                            gender = "Nữ",
                            lastName = "Hà",
                            userID = 10
                        },
                        new
                        {
                            profileID = 11,
                            firstName = "Bùi Thị",
                            gender = "Nữ",
                            lastName = "Linh",
                            userID = 11
                        },
                        new
                        {
                            profileID = 12,
                            firstName = "Đỗ Văn",
                            gender = "Nam",
                            lastName = "Tài",
                            userID = 12
                        },
                        new
                        {
                            profileID = 13,
                            firstName = "Nguyễn Công",
                            gender = "Nam",
                            lastName = "Minh",
                            userID = 13
                        },
                        new
                        {
                            profileID = 14,
                            firstName = "Hà Thị",
                            gender = "Nữ",
                            lastName = "Loan",
                            userID = 14
                        },
                        new
                        {
                            profileID = 15,
                            firstName = "Lý Minh",
                            gender = "Nam",
                            lastName = "Quân",
                            userID = 15
                        },
                        new
                        {
                            profileID = 16,
                            firstName = "Đinh Thị Bích",
                            gender = "Nữ",
                            lastName = "Ngọc",
                            userID = 16
                        },
                        new
                        {
                            profileID = 17,
                            firstName = "Phan Hữu",
                            gender = "Nam",
                            lastName = "Phước",
                            userID = 17
                        },
                        new
                        {
                            profileID = 18,
                            firstName = "Vũ Thị Thùy",
                            gender = "Nữ",
                            lastName = "Dung",
                            userID = 18
                        },
                        new
                        {
                            profileID = 19,
                            firstName = "Cao Ngọc",
                            gender = "Nữ",
                            lastName = "Anh",
                            userID = 19
                        },
                        new
                        {
                            profileID = 20,
                            firstName = "Đặng Hữu",
                            gender = "Nam",
                            lastName = "Thành",
                            userID = 20
                        },
                        new
                        {
                            profileID = 21,
                            firstName = "Nguyễn Văn",
                            gender = "Nam",
                            lastName = "Dũng",
                            userID = 21
                        },
                        new
                        {
                            profileID = 22,
                            firstName = "Trần Thị Kim",
                            gender = "Nữ",
                            lastName = "Oanh",
                            userID = 22
                        },
                        new
                        {
                            profileID = 23,
                            firstName = "Lê Hoàng",
                            gender = "Nam",
                            lastName = "Nam",
                            userID = 23
                        },
                        new
                        {
                            profileID = 24,
                            firstName = "Phạm Tuấn",
                            gender = "Nam",
                            lastName = "Anh",
                            userID = 24
                        },
                        new
                        {
                            profileID = 25,
                            firstName = "Vũ Đức",
                            gender = "Nam",
                            lastName = "Mạnh",
                            userID = 25
                        },
                        new
                        {
                            profileID = 26,
                            firstName = "Hoàng Thị",
                            gender = "Nữ",
                            lastName = "Hồng",
                            userID = 26
                        },
                        new
                        {
                            profileID = 27,
                            firstName = "Bùi Thanh",
                            gender = "Nam",
                            lastName = "Phong",
                            userID = 27
                        },
                        new
                        {
                            profileID = 28,
                            firstName = "Đỗ Thành",
                            gender = "Nam",
                            lastName = "Đạt",
                            userID = 28
                        },
                        new
                        {
                            profileID = 29,
                            firstName = "Lưu Thị Bảo",
                            gender = "Nữ",
                            lastName = "Châu",
                            userID = 29
                        },
                        new
                        {
                            profileID = 30,
                            firstName = "Vũ Thành",
                            gender = "Nam",
                            lastName = "Long",
                            userID = 30
                        },
                        new
                        {
                            profileID = 31,
                            firstName = "Nguyễn Bá",
                            gender = "Nam",
                            lastName = "Kiên",
                            userID = 31
                        },
                        new
                        {
                            profileID = 32,
                            firstName = "Trần Thị",
                            gender = "Nữ",
                            lastName = "Phương",
                            userID = 32
                        },
                        new
                        {
                            profileID = 33,
                            firstName = "Phan Ngọc",
                            gender = "Nữ",
                            lastName = "Yến",
                            userID = 33
                        },
                        new
                        {
                            profileID = 34,
                            firstName = "Cao Thị",
                            gender = "Nữ",
                            lastName = "Bích",
                            userID = 34
                        },
                        new
                        {
                            profileID = 35,
                            firstName = "Trương Văn",
                            gender = "Nam",
                            lastName = "Khải",
                            userID = 35
                        });
                });

            modelBuilder.Entity("TH.Auth.Domain.User.AuthUser", b =>
                {
                    b.Property<int>("userID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("userID"));

                    b.Property<DateTime>("createdAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("departmentID")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("googleSub")
                        .HasColumnType("text");

                    b.Property<bool>("isEmailVerified")
                        .HasColumnType("boolean");

                    b.Property<string>("passwordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("phoneNumber")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("scope")
                        .HasColumnType("text");

                    b.Property<string>("status")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("tokenVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("updatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("userName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("userID");

                    b.HasIndex("email")
                        .IsUnique();

                    b.HasIndex("userName")
                        .IsUnique();

                    b.ToTable("AuthUser", "auth");

                    b.HasData(
                        new
                        {
                            userID = 1,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "1",
                            email = "pqhung@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0901234001",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "pham.quoc.hung"
                        },
                        new
                        {
                            userID = 2,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "1",
                            email = "tttung@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0901234002",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "tran.thanh.tung"
                        },
                        new
                        {
                            userID = 3,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "1",
                            email = "nmchau@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0901234003",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "nguyen.minh.chau"
                        },
                        new
                        {
                            userID = 4,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "1",
                            email = "lqbinh@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0901234004",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "le.quang.binh"
                        },
                        new
                        {
                            userID = 5,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "2",
                            email = "nthuong.kt@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0902234001",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "nguyen.thi.huong"
                        },
                        new
                        {
                            userID = 6,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "2",
                            email = "lbngoc.kt@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0902234002",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "le.bao.ngoc"
                        },
                        new
                        {
                            userID = 7,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "2",
                            email = "tvhai.kt@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0902234003",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "tran.van.hai"
                        },
                        new
                        {
                            userID = 8,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "2",
                            email = "ptmai.kt@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0902234004",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "pham.thi.mai"
                        },
                        new
                        {
                            userID = 9,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "2",
                            email = "vxtruong.kt@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0902234005",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "vo.xuan.truong"
                        },
                        new
                        {
                            userID = 10,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "3",
                            email = "htha.ns@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0903234001",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "hoang.thu.ha"
                        },
                        new
                        {
                            userID = 11,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "3",
                            email = "btlinh.ns@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0903234002",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "bui.thi.linh"
                        },
                        new
                        {
                            userID = 12,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "4",
                            email = "dvtai.tech@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0904234001",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "do.van.tai"
                        },
                        new
                        {
                            userID = 13,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "4",
                            email = "ncminh.tech@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0904234002",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "nguyen.cong.minh"
                        },
                        new
                        {
                            userID = 14,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "4",
                            email = "htloan.tech@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0904234003",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "ha.thi.loan"
                        },
                        new
                        {
                            userID = 15,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "5",
                            email = "lmquan.prod@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0905234001",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "ly.minh.quan"
                        },
                        new
                        {
                            userID = 16,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "5",
                            email = "dtbngoc.prod@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0905234002",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "dinh.thi.bich.ngoc"
                        },
                        new
                        {
                            userID = 17,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "5",
                            email = "phphuoc.prod@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0905234003",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "phan.huu.phuoc"
                        },
                        new
                        {
                            userID = 18,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "5",
                            email = "vttdung.prod@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0905234004",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "vu.thi.thuy.dung"
                        },
                        new
                        {
                            userID = 19,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "5",
                            email = "cnanh.prod@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0905234005",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "cao.ngoc.anh"
                        },
                        new
                        {
                            userID = 20,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "6",
                            email = "dhthanh.dev@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0906234001",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "dang.huu.thanh"
                        },
                        new
                        {
                            userID = 21,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "6",
                            email = "nvdung.dev@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0906234002",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "nguyen.van.dung"
                        },
                        new
                        {
                            userID = 22,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "6",
                            email = "ttkoanh.dev@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0906234003",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "tran.thi.kim.oanh"
                        },
                        new
                        {
                            userID = 23,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "6",
                            email = "lhnam.dev@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0906234004",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "le.hoang.nam"
                        },
                        new
                        {
                            userID = 24,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "6",
                            email = "ptanh.dev@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0906234005",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "pham.tuan.anh"
                        },
                        new
                        {
                            userID = 25,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "6",
                            email = "vdmanh.dev@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0906234006",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "vu.duc.manh"
                        },
                        new
                        {
                            userID = 26,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "6",
                            email = "hthong.dev@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0906234007",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "hoang.thi.hong"
                        },
                        new
                        {
                            userID = 27,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "6",
                            email = "btphong.dev@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0906234008",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "bui.thanh.phong"
                        },
                        new
                        {
                            userID = 28,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "6",
                            email = "dtdat.dev@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0906234009",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "do.thanh.dat"
                        },
                        new
                        {
                            userID = 29,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "6",
                            email = "ltbchau.dev@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0906234010",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "luu.thi.bao.chau"
                        },
                        new
                        {
                            userID = 30,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "7",
                            email = "vtlong.pmo@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0907234001",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "vu.thanh.long"
                        },
                        new
                        {
                            userID = 31,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "7",
                            email = "nbkien.pmo@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0907234002",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "nguyen.ba.kien"
                        },
                        new
                        {
                            userID = 32,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "7",
                            email = "ttphuong.pmo@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0907234003",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "tran.thi.phuong"
                        },
                        new
                        {
                            userID = 33,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "8",
                            email = "pnyen.design@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0908234001",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "phan.ngoc.yen"
                        },
                        new
                        {
                            userID = 34,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "8",
                            email = "ctbich.design@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0908234002",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "cao.thi.bich"
                        },
                        new
                        {
                            userID = 35,
                            createdAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            departmentID = "8",
                            email = "tvkhai.design@thtech.vn",
                            isEmailVerified = true,
                            passwordHash = "$2a$11$hLyVHfCp0KoZ3XU5Qf8C7OeGUv8RqKLNz2wYA1mS3nXbP4dJ6iG6",
                            phoneNumber = "0908234003",
                            scope = "staff",
                            status = "Active",
                            tokenVersion = 1,
                            updatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            userName = "truong.van.khai"
                        });
                });

            modelBuilder.Entity("TH.Auth.Domain.MFA.AuthAuditLog", b =>
                {
                    b.HasOne("TH.Auth.Domain.User.AuthUser", "user")
                        .WithMany("auditLogs")
                        .HasForeignKey("userID");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TH.Auth.Domain.MFA.AuthMfaSecret", b =>
                {
                    b.HasOne("TH.Auth.Domain.User.AuthUser", "user")
                        .WithOne("mfaSecret")
                        .HasForeignKey("TH.Auth.Domain.MFA.AuthMfaSecret", "userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("TH.Auth.Domain.MFA.AuthUserSession", b =>
                {
                    b.HasOne("TH.Auth.Domain.User.AuthUser", "user")
                        .WithMany("sessions")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("TH.Auth.Domain.Role.AuthRolePermission", b =>
                {
                    b.HasOne("TH.Auth.Domain.Role.AuthPermission", "permission")
                        .WithMany("rolePermissions")
                        .HasForeignKey("permissionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TH.Auth.Domain.Role.AuthRole", "role")
                        .WithMany("rolePermissions")
                        .HasForeignKey("roleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("permission");

                    b.Navigation("role");
                });

            modelBuilder.Entity("TH.Auth.Domain.Role.AuthUserRole", b =>
                {
                    b.HasOne("TH.Auth.Domain.Role.AuthRole", "role")
                        .WithMany("userRoles")
                        .HasForeignKey("roleID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TH.Auth.Domain.User.AuthUser", "user")
                        .WithMany("userRoles")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TH.Auth.Domain.Token.AuthEmailVerification", b =>
                {
                    b.HasOne("TH.Auth.Domain.User.AuthUser", "user")
                        .WithMany("emailVerifications")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("TH.Auth.Domain.Token.AuthPasswordReset", b =>
                {
                    b.HasOne("TH.Auth.Domain.User.AuthUser", "user")
                        .WithMany("passwordResets")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("TH.Auth.Domain.Token.AuthRefreshToken", b =>
                {
                    b.HasOne("TH.Auth.Domain.MFA.AuthUserSession", "session")
                        .WithMany("refreshTokens")
                        .HasForeignKey("sessionID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TH.Auth.Domain.User.AuthUser", "user")
                        .WithMany("refreshTokens")
                        .HasForeignKey("userID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("session");

                    b.Navigation("user");
                });

            modelBuilder.Entity("TH.Auth.Domain.User.AuthProfile", b =>
                {
                    b.HasOne("TH.Auth.Domain.User.AuthUser", "user")
                        .WithOne("profile")
                        .HasForeignKey("TH.Auth.Domain.User.AuthProfile", "userID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("TH.Auth.Domain.MFA.AuthUserSession", b =>
                {
                    b.Navigation("refreshTokens");
                });

            modelBuilder.Entity("TH.Auth.Domain.Role.AuthPermission", b =>
                {
                    b.Navigation("rolePermissions");
                });

            modelBuilder.Entity("TH.Auth.Domain.Role.AuthRole", b =>
                {
                    b.Navigation("rolePermissions");

                    b.Navigation("userRoles");
                });

            modelBuilder.Entity("TH.Auth.Domain.User.AuthUser", b =>
                {
                    b.Navigation("auditLogs");

                    b.Navigation("emailVerifications");

                    b.Navigation("mfaSecret");

                    b.Navigation("passwordResets");

                    b.Navigation("profile");

                    b.Navigation("refreshTokens");

                    b.Navigation("sessions");

                    b.Navigation("userRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
